# Generated by Django 3.0 on 2022-04-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20220424_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liked_videos',
            field=models.ManyToManyField(related_name='user_liked_videos', to='core.Video'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saved_playlists',
            field=models.ManyToManyField(to='core.Playlist'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscribed_channels',
            field=models.ManyToManyField(to='core.Channel'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='viewed_videos',
            field=models.ManyToManyField(related_name='user_viewed_videos', to='core.Video'),
        ),
    ]
