# Generated by Django 3.0 on 2022-04-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20220424_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='srt_file',
            field=models.FileField(null=True, upload_to='srt/'),
        ),
    ]
